version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8765:8765"
    volumes:
      - ./backend:/app
    # depends_on:
    #   - db

  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: flask_user
  #     POSTGRES_PASSWORD: flask_password
  #     POSTGRES_DB: flask_db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
# volumes:
#   postgres_data:
