version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app
    environment:
      PORT: ${BACKEND_PORT}
      FRONTEND_URL: ${FRONTEND_URL}
    networks:
      - sail

    # depends_on:
    #   - db

  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: flask_user
  #     POSTGRES_PASSWORD: flask_password
  #     POSTGRES_DB: flask_db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
# volumes:
#   postgres_data:

networks:
  sail:
    driver: bridge
